var PRODUCTS_SEED = [
  {
    id: 1,
    name: "STM32H750 开发板",
    desc: "480MHz Cortex-M7，1MB Flash，外置 SDRAM，适合高性能嵌入式应用",
    price: 189,
    tag: "热卖",
    category: "MCU 开发板",
    categoryId: "cat-mcu",
    img: "/images/stm32.jpg",
    intro:
      "基于 ST 官方 STM32H750VBT6 的高性能 MCU 开发板，主频可达 480MHz，片内 1MB Flash、562KB SRAM，板载外扩 SDRAM，适合 GUI、音频、工业控制与实时算法验证。提供完整原理图、原理图封装与示例工程，开箱即可调试。",
    features: [
      "Cortex-M7 @ 480MHz，双精度 FPU，DSP 指令集",
      "板载 8MB SDRAM，方便 LVGL / 帧缓冲应用",
      "USB-C 供电与下载，板载 ST-Link 兼容电路",
      "丰富外设：UART / SPI / I2C / CAN / SDMMC / DCMI",
      "预留 LCD / 摄像头 / 以太网接口焊盘",
      "提供 HAL / CubeMX 例程与引脚对照表",
    ],
    specs: [
      ["主控", "STM32H750VBT6"],
      ["架构", "Arm Cortex-M7"],
      ["主频", "最高 480 MHz"],
      ["Flash / RAM", "1MB / 562KB + 外扩 SDRAM"],
      ["供电", "5V USB-C / 3.3V 稳压"],
      ["尺寸", "约 70 × 50 mm"],
    ],
    pins: [
      ["PA0", "ADC1_IN0 / TIM2_CH1", "模拟采集或定时器输出"],
      ["PA9 / PA10", "USART1_TX / RX", "调试串口默认"],
      ["PB6 / PB7", "I2C1_SCL / SDA", "传感器总线"],
      ["PC10–PC12", "SPI3", "外设扩展"],
      ["PD0 / PD1", "CAN1_RX / TX", "工业现场总线"],
      ["PE2–PE6", "FMC", "外扩 SDRAM 地址/数据"],
      ["3V3 / GND", "电源", "外设供电，注意电流"],
      ["5V", "USB 输入", "经稳压到 3.3V"],
    ],
    package: ["开发板本体 ×1", "USB-C 数据线 ×1", "排针（部分已焊）", "快速入门说明"],
    downloads: [
      { name: "技术资料包 (ZIP)", file: "/downloads/stm32h750-docs.zip", format: "ZIP" },
      { name: "技术资料包 (7Z)", file: "/downloads/stm32h750-docs.7z", format: "7Z" },
    ],
  },
  {
    id: 2,
    name: "ESP32-S3 开发套件",
    desc: "WiFi + BLE 5.0，双核 240MHz，内置 AI 加速，IoT 首选",
    price: 68,
    tag: "推荐",
    category: "无线 IoT",
    categoryId: "cat-iot",
    img: "/images/esp32.jpg",
    intro:
      "乐鑫 ESP32-S3 双核 Xtensa LX7 开发套件，集成 2.4GHz Wi‑Fi 与 Bluetooth LE 5，片内向量指令适合轻量 AI 推理与语音唤醒。板载 USB 原生下载、RGB LED 与扩展排针，兼容 Arduino / ESP-IDF / MicroPython。",
    features: [
      "双核 LX7 @ 240MHz，支持向量扩展",
      "Wi‑Fi 802.11 b/g/n + Bluetooth LE 5",
      "原生 USB OTG，免外置 USB‑UART 芯片下载",
      "充足 GPIO，支持摄像头 / LCD / I2S 音频",
      "板载 Boot / Reset 按键与状态灯",
      "提供 ESP-IDF 与 Arduino 示例",
    ],
    specs: [
      ["模组", "ESP32-S3-WROOM"],
      ["主频", "最高 240 MHz"],
      ["无线", "Wi‑Fi + BLE 5"],
      ["Flash", "常见 8MB / 16MB（以实物丝印为准）"],
      ["供电", "5V USB / 3.3V"],
      ["工作温度", "-40 ~ 85°C（芯片规格）"],
    ],
    pins: [
      ["GPIO1 / GPIO2", "UART0 TX / RX", "默认调试串口"],
      ["GPIO8 / GPIO9", "I2C", "常用传感器接口"],
      ["GPIO11–GPIO13", "SPI", "Flash / 屏 / 外设"],
      ["GPIO19 / GPIO20", "USB D- / D+", "原生 USB"],
      ["GPIO38–GPIO42", "摄像头 DVP", "需配合排线"],
      ["3V3 / GND", "电源", "外设供电"],
      ["EN", "使能 / 复位", "低电平复位"],
      ["BOOT", "启动模式", "下载时按住"],
    ],
    package: ["开发板 ×1", "USB 线 ×1", "说明书二维码"],
    downloads: [
      { name: "技术资料包 (ZIP)", file: "/downloads/esp32-s3-docs.zip", format: "ZIP" },
      { name: "技术资料包 (7Z)", file: "/downloads/esp32-s3-docs.7z", format: "7Z" },
    ],
  },
  {
    id: 4,
    name: "LVGL 触摸屏套件",
    desc: "4.3 寸 IPS 电容屏 + STM32F429，预装 LVGL 图形库 Demo",
    price: 258,
    tag: "套装",
    category: "显示套件",
    categoryId: "cat-display",
    img: "/images/lvgl.jpg",
    intro:
      "4.3 寸 IPS 电容触摸屏与 STM32F429 核心板组合套件，出厂预烧录 LVGL Demo，适合人机界面（HMI）、仪表盘与嵌入式 UI 学习。提供触摸校准、控件示例与字体工程模板。",
    features: [
      "4.3\" IPS，常见分辨率 800×480",
      "电容多点触控，I2C 触摸控制器",
      "STM32F429，带 TFT 控制器接口",
      "预装 LVGL 演示：按钮、列表、图表",
      "可外接串口调试与 SD 卡资源",
      "提供完整 UI 工程源码包",
    ],
    specs: [
      ["屏幕", "4.3 寸 IPS 电容屏"],
      ["分辨率", "800 × 480（典型）"],
      ["主控", "STM32F429"],
      ["触摸", "电容，I2C"],
      ["图形库", "LVGL"],
      ["接口", "排线座 / 扩展针"],
    ],
    pins: [
      ["LCD_R0–R7", "红色数据", "RGB 并行接口"],
      ["LCD_G0–G7", "绿色数据", "RGB 并行接口"],
      ["LCD_B0–B7", "蓝色数据", "RGB 并行接口"],
      ["LCD_CLK / DE / HSYNC / VSYNC", "时序", "显示同步信号"],
      ["CTP_SCL / SDA", "触摸 I2C", "电容触摸通信"],
      ["CTP_INT / RST", "中断 / 复位", "触摸事件与复位"],
      ["USART1", "调试串口", "日志与命令"],
      ["3V3 / GND / 5V", "电源", "注意背光电流"],
    ],
    package: ["核心板 ×1", "4.3 寸触摸屏 ×1", "排线 ×1", "示例资料链接"],
    downloads: [
      { name: "技术资料包 (ZIP)", file: "/downloads/lvgl-kit-docs.zip", format: "ZIP" },
      { name: "技术资料包 (7Z)", file: "/downloads/lvgl-kit-docs.7z", format: "7Z" },
    ],
  },
  {
    id: 5,
    name: "MPU6050 传感器模块",
    desc: "六轴陀螺仪 + 加速度计，I2C 接口，姿态检测必备",
    price: 12,
    tag: "传感器",
    category: "传感器",
    categoryId: "cat-sensor",
    img: "/images/mpu6050.jpg",
    intro:
      "基于 InvenSense MPU-6050 的六轴运动传感器模块，集成三轴陀螺仪与三轴加速度计，I2C 数字输出。常用于平衡车、姿态解算、手势识别与无人机飞控入门实验。",
    features: [
      "三轴陀螺仪 + 三轴加速度计",
      "I2C 接口，地址可选",
      "板载 3.3V LDO，可用 5V 供电",
      "引出 INT 中断脚",
      "兼容 Arduino / STM32 / ESP32 例程",
      "体积小，面包板友好",
    ],
    specs: [
      ["芯片", "MPU-6050"],
      ["接口", "I2C"],
      ["加速度量程", "±2/±4/±8/±16 g"],
      ["陀螺仪量程", "±250/±500/±1000/±2000 °/s"],
      ["供电", "3.3V / 5V"],
      ["尺寸", "约 15 × 25 mm"],
    ],
    pins: [
      ["VCC", "电源", "3.3V 或 5V"],
      ["GND", "地", "与主控共地"],
      ["SCL", "I2C 时钟", "接主控 SCL，建议上拉"],
      ["SDA", "I2C 数据", "接主控 SDA，建议上拉"],
      ["XDA / XCL", "辅 I2C", "可挂从传感器（可选）"],
      ["AD0", "地址选择", "接 GND 为 0x68，接 VCC 为 0x69"],
      ["INT", "中断输出", "数据就绪 / 运动中断"],
    ],
    package: ["MPU6050 模块 ×1", "直插排针"],
    downloads: [
      { name: "技术资料包 (ZIP)", file: "/downloads/mpu6050-docs.zip", format: "ZIP" },
      { name: "技术资料包 (7Z)", file: "/downloads/mpu6050-docs.7z", format: "7Z" },
    ],
  },
];

if (typeof window !== "undefined") window.PRODUCTS = PRODUCTS_SEED;
if (typeof module !== "undefined" && module.exports) module.exports = PRODUCTS_SEED;

