window.PRODUCTS = [
  {
    id: 1,
    name: "STM32H750 开发板",
    desc: "480MHz Cortex-M7，1MB Flash，外置 SDRAM，适合高性能嵌入式应用",
    price: 189,
    tag: "热卖",
    category: "MCU 开发板",
    categoryId: "cat-mcu",
    img: "/images/stm32.jpg",
    intro:
      "基于 ST 官方 STM32H750VBT6 的高性能 MCU 开发板，主频可达 480MHz，片内 1MB Flash、562KB SRAM，板载外扩 SDRAM，适合 GUI、音频、工业控制与实时算法验证。提供完整原理图、原理图封装与示例工程，开箱即可调试。",
    features: [
      "Cortex-M7 @ 480MHz，双精度 FPU，DSP 指令集",
      "板载 8MB SDRAM，方便 LVGL / 帧缓冲应用",
      "USB-C 供电与下载，板载 ST-Link 兼容电路",
      "丰富外设：UART / SPI / I2C / CAN / SDMMC / DCMI",
      "预留 LCD / 摄像头 / 以太网接口焊盘",
      "提供 HAL / CubeMX 例程与引脚对照表",
    ],
    specs: [
      ["主控", "STM32H750VBT6"],
      ["架构", "Arm Cortex-M7"],
      ["主频", "最高 480 MHz"],
      ["Flash / RAM", "1MB / 562KB + 外扩 SDRAM"],
      ["供电", "5V USB-C / 3.3V 稳压"],
      ["尺寸", "约 70 × 50 mm"],
    ],
    pins: [
      ["PA0", "ADC1_IN0 / TIM2_CH1", "模拟采集或定时器输出"],
      ["PA9 / PA10", "USART1_TX / RX", "调试串口默认"],
      ["PB6 / PB7", "I2C1_SCL / SDA", "传感器总线"],
      ["PC10–PC12", "SPI3", "外设扩展"],
      ["PD0 / PD1", "CAN1_RX / TX", "工业现场总线"],
      ["PE2–PE6", "FMC", "外扩 SDRAM 地址/数据"],
      ["3V3 / GND", "电源", "外设供电，注意电流"],
      ["5V", "USB 输入", "经稳压到 3.3V"],
    ],
    package: ["开发板本体 ×1", "USB-C 数据线 ×1", "排针（部分已焊）", "快速入门说明"],
  },
  {
    id: 2,
    name: "ESP32-S3 开发套件",
    desc: "WiFi + BLE 5.0，双核 240MHz，内置 AI 加速，IoT 首选",
    price: 68,
    tag: "推荐",
    category: "无线 IoT",
    categoryId: "cat-iot",
    img: "/images/esp32.jpg",
    intro:
      "乐鑫 ESP32-S3 双核 Xtensa LX7 开发套件，集成 2.4GHz Wi‑Fi 与 Bluetooth LE 5，片内向量指令适合轻量 AI 推理与语音唤醒。板载 USB 原生下载、RGB LED 与扩展排针，兼容 Arduino / ESP-IDF / MicroPython。",
    features: [
      "双核 LX7 @ 240MHz，支持向量扩展",
      "Wi‑Fi 802.11 b/g/n + Bluetooth LE 5",
      "原生 USB OTG，免外置 USB‑UART 芯片下载",
      "充足 GPIO，支持摄像头 / LCD / I2S 音频",
      "板载 Boot / Reset 按键与状态灯",
      "提供 ESP-IDF 与 Arduino 示例",
    ],
    specs: [
      ["模组", "ESP32-S3-WROOM"],
      ["主频", "最高 240 MHz"],
      ["无线", "Wi‑Fi + BLE 5"],
      ["Flash", "常见 8MB / 16MB（以实物丝印为准）"],
      ["供电", "5V USB / 3.3V"],
      ["工作温度", "-40 ~ 85°C（芯片规格）"],
    ],
    pins: [
      ["GPIO1 / GPIO2", "UART0 TX / RX", "默认调试串口"],
      ["GPIO8 / GPIO9", "I2C", "常用传感器接口"],
      ["GPIO11–GPIO13", "SPI", "Flash / 屏 / 外设"],
      ["GPIO19 / GPIO20", "USB D- / D+", "原生 USB"],
      ["GPIO38–GPIO42", "摄像头 DVP", "需配合排线"],
      ["3V3 / GND", "电源", "外设供电"],
      ["EN", "使能 / 复位", "低电平复位"],
      ["BOOT", "启动模式", "下载时按住"],
    ],
    package: ["开发板 ×1", "USB 线 ×1", "说明书二维码"],
  },
  {
    id: 3,
    name: "Raspberry Pi 5 主板",
    desc: "博通 BCM2712 四核 2.4GHz，8GB RAM，PCIe 2.0 接口",
    price: 599,
    tag: "新品",
    category: "单板计算机",
    categoryId: "cat-sbc",
    img: "/images/rpi5.jpg",
    intro:
      "树莓派 5 采用 Broadcom BCM2712 四核 Cortex-A76 @ 2.4GHz，可选 8GB LPDDR4X 内存，新增 PCIe 2.0 接口可外接 NVMe SSD。双 4K 显示、千兆网口与更快的 USB 3.0，适合桌面 Linux、边缘计算与机器人主控。",
    features: [
      "四核 A76 @ 2.4GHz，性能大幅提升",
      "双 micro-HDMI，最高双 4K60",
      "PCIe 2.0 ×1，可接 M.2 NVMe（需扩展板）",
      "千兆以太网 + 双频 Wi‑Fi / 蓝牙",
      "2× USB 3.0 + 2× USB 2.0",
      "40-pin GPIO 兼容树莓派生态",
    ],
    specs: [
      ["SoC", "BCM2712"],
      ["CPU", "4× Cortex-A76 @ 2.4GHz"],
      ["内存", "8GB LPDDR4X"],
      ["存储", "microSD + PCIe 扩展"],
      ["视频", "2× micro-HDMI"],
      ["供电", "建议 5V/5A USB-C PD"],
    ],
    pins: [
      ["Pin 1 / 17", "3.3V", "逻辑电源，勿超电流"],
      ["Pin 2 / 4", "5V", "外设供电"],
      ["Pin 3 / 5", "GPIO2 / 3 (SDA/SCL)", "I2C1"],
      ["Pin 8 / 10", "GPIO14 / 15", "UART0 TX / RX"],
      ["Pin 19 / 21 / 23", "MOSI / MISO / SCLK", "SPI0"],
      ["Pin 6 / 9 / 14…", "GND", "接地"],
      ["Pin 32 / 33", "PWM", "舵机 / 调光"],
      ["Pin 37–40", "通用 GPIO", "输入输出可配置"],
    ],
    package: ["树莓派 5 主板 ×1（不含电源/外壳/卡）", "防静电包装"],
  },
  {
    id: 4,
    name: "LVGL 触摸屏套件",
    desc: "4.3 寸 IPS 电容屏 + STM32F429，预装 LVGL 图形库 Demo",
    price: 258,
    tag: "套装",
    category: "显示套件",
    categoryId: "cat-display",
    img: "/images/lvgl.jpg",
    intro:
      "4.3 寸 IPS 电容触摸屏与 STM32F429 核心板组合套件，出厂预烧录 LVGL Demo，适合人机界面（HMI）、仪表盘与嵌入式 UI 学习。提供触摸校准、控件示例与字体工程模板。",
    features: [
      "4.3\" IPS，常见分辨率 800×480",
      "电容多点触控，I2C 触摸控制器",
      "STM32F429，带 TFT 控制器接口",
      "预装 LVGL 演示：按钮、列表、图表",
      "可外接串口调试与 SD 卡资源",
      "提供完整 UI 工程源码包",
    ],
    specs: [
      ["屏幕", "4.3 寸 IPS 电容屏"],
      ["分辨率", "800 × 480（典型）"],
      ["主控", "STM32F429"],
      ["触摸", "电容，I2C"],
      ["图形库", "LVGL"],
      ["接口", "排线座 / 扩展针"],
    ],
    pins: [
      ["LCD_R0–R7", "红色数据", "RGB 并行接口"],
      ["LCD_G0–G7", "绿色数据", "RGB 并行接口"],
      ["LCD_B0–B7", "蓝色数据", "RGB 并行接口"],
      ["LCD_CLK / DE / HSYNC / VSYNC", "时序", "显示同步信号"],
      ["CTP_SCL / SDA", "触摸 I2C", "电容触摸通信"],
      ["CTP_INT / RST", "中断 / 复位", "触摸事件与复位"],
      ["USART1", "调试串口", "日志与命令"],
      ["3V3 / GND / 5V", "电源", "注意背光电流"],
    ],
    package: ["核心板 ×1", "4.3 寸触摸屏 ×1", "排线 ×1", "示例资料链接"],
  },
  {
    id: 5,
    name: "MPU6050 传感器模块",
    desc: "六轴陀螺仪 + 加速度计，I2C 接口，姿态检测必备",
    price: 12,
    tag: "传感器",
    category: "传感器",
    categoryId: "cat-sensor",
    img: "/images/mpu6050.jpg",
    intro:
      "基于 InvenSense MPU-6050 的六轴运动传感器模块，集成三轴陀螺仪与三轴加速度计，I2C 数字输出。常用于平衡车、姿态解算、手势识别与无人机飞控入门实验。",
    features: [
      "三轴陀螺仪 + 三轴加速度计",
      "I2C 接口，地址可选",
      "板载 3.3V LDO，可用 5V 供电",
      "引出 INT 中断脚",
      "兼容 Arduino / STM32 / ESP32 例程",
      "体积小，面包板友好",
    ],
    specs: [
      ["芯片", "MPU-6050"],
      ["接口", "I2C"],
      ["加速度量程", "±2/±4/±8/±16 g"],
      ["陀螺仪量程", "±250/±500/±1000/±2000 °/s"],
      ["供电", "3.3V / 5V"],
      ["尺寸", "约 15 × 25 mm"],
    ],
    pins: [
      ["VCC", "电源", "3.3V 或 5V"],
      ["GND", "地", "与主控共地"],
      ["SCL", "I2C 时钟", "接主控 SCL，建议上拉"],
      ["SDA", "I2C 数据", "接主控 SDA，建议上拉"],
      ["XDA / XCL", "辅 I2C", "可挂从传感器（可选）"],
      ["AD0", "地址选择", "接 GND 为 0x68，接 VCC 为 0x69"],
      ["INT", "中断输出", "数据就绪 / 运动中断"],
    ],
    package: ["MPU6050 模块 ×1", "直插排针"],
  },
  {
    id: 6,
    name: "Arduino UNO R4 WiFi",
    desc: "Renesas RA4M1 芯片，内置 WiFi，兼容 Arduino 生态",
    price: 145,
    tag: "入门",
    category: "MCU 开发板",
    categoryId: "cat-mcu",
    img: "/images/arduino.jpg",
    intro:
      "Arduino UNO R4 WiFi 采用 Renesas RA4M1（Cortex-M4）与 ESP32-S3 协处理器，在保留经典 UNO 外形与 5V 逻辑的同时提供 Wi‑Fi / 蓝牙。兼容大量现有 Arduino 盾板与教程，适合教学与快速原型。",
    features: [
      "RA4M1 @ 48MHz，SRAM / Flash 更大",
      "板载 ESP32-S3，Wi‑Fi + 蓝牙",
      "12×8 LED 矩阵，可做简单显示",
      "DAC、CAN、RTC 等更丰富外设",
      "USB-C，兼容 UNO 盾板布局",
      "官方 IDE 与库完善",
    ],
    specs: [
      ["主控", "Renesas RA4M1"],
      ["协处理", "ESP32-S3（无线）"],
      ["逻辑电平", "5V"],
      ["工作电压", "5V（USB-C / 电源座）"],
      ["数字 I/O", "14（含 PWM）"],
      ["模拟输入", "6 路"],
    ],
    pins: [
      ["D0 / D1", "RX / TX", "硬件串口（与 USB 复用注意）"],
      ["D2–D13", "数字 I/O", "其中部分支持 PWM"],
      ["A0–A5", "模拟输入", "也可作数字口"],
      ["SCL / SDA", "I2C", "另有专用针或 A4/A5"],
      ["VIN", "外电输入", "约 6–24V，经稳压"],
      ["5V / 3.3V / GND", "电源", "给盾板与模块供电"],
      ["IOREF", "参考电平", "5V，兼容盾板"],
      ["RESET", "复位", "低电平复位"],
    ],
    package: ["UNO R4 WiFi 板 ×1", "包装盒"],
  },
];

